import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8938%3A9938",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "show1stSubNav": figma.boolean('show 1st subNav'),
      // "show2ndSubNav": figma.boolean('show 2nd subNav'),
      // "show3rdSubNav": figma.boolean('show 3rd subNav'),
      // "show4thSubNav": figma.boolean('show 4th subNav'),
      // "show5thSubNav": figma.boolean('show 5th subNav'),
      // "show6thSubNav": figma.boolean('show 6th subNav'),
      // "show7thSubNav": figma.boolean('show 7th subNav'),
      // "quantity": figma.enum('quantity', {
      //   "2 navItems": "2-navitems",
      //   "3 navItems": "3-navitems",
      //   "4 navItems": "4-navitems",
      //   "5 navItems": "5-navitems",
      //   "6 navItems": "6-navitems",
      //   "7 navItems": "7-navitems"
      // }),
      // "activeNav": figma.enum('activeNav', {
      //   "-": "-",
      //   "first": "first",
      //   "second": "second",
      //   "third": "third",
      //   "fourth": "fourth",
      //   "fifth": "fifth",
      //   "sixth": "sixth",
      //   "seventh": "seventh"
      // }),
      // "hoveredNav": figma.enum('hoveredNav', {
      //   "-": "-",
      //   "first": "first",
      //   "second": "second",
      //   "third": "third",
      //   "fourth": "fourth",
      //   "fifth": "fifth",
      //   "sixth": "sixth",
      //   "seventh": "seventh"
      // })
    },
    example: (_props) => <Index items={[]} />,
  }
);
