import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=13583%3A10292",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      hasInvertedStyle: figma.boolean("hasInvertedStyle?"),
      logo: figma.instance("↪️ logoSlot"),
      // No matching props could be found for these Figma properties:
      // "showPrimaryLogoText": figma.boolean('showPrimaryLogoText?'),
      // "logoSlot": figma.instance('↪️ logoSlot'),
      // "showPrimaryLogoSlot": figma.boolean('showPrimaryLogoSlot?'),
      // "showDivider": figma.boolean('showDivider?'),
      // "showPrimaryLogoTag": figma.boolean('showPrimaryLogoTag?'),
      // "showSecondaryLogos": figma.boolean('showSecondaryLogos?'),
      // "showLinks": figma.boolean('showLinks?'),
      // "sdsType": figma.enum('sdsType', {
      //   "wide": "wide",
      //   "narrow": "narrow"
      // })
    },
    example: (props) => (
      <Index
        hasInvertedStyle={props.hasInvertedStyle}
        logo={props.logo}
        title={/* TODO */}
      />
    ),
  }
);
