import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=15429%3A36061",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      square: figma.boolean("showVisualElement?"),
      image: figma.enum("↪️ imagePadding", {
        false: false,
        true: true,
      }),
      imagePosition: figma.enum("↪️ imagePosition", {
        left: "left",
        right: "right",
      }),
      imagePadding: figma.enum("↪️ imagePadding", {
        false: false,
        true: true,
      }),
      sdsType: figma.enum("sdsType", {
        wide: "wide",
        narrow: "narrow",
      }),
      titleText: figma.instance("↪️ titleSlotElement"),
      boundingBox: figma.boolean("showBoundingBox?"),
      decorativeBorder: figma.boolean("showDecorativeBorder?"),
      // No matching props could be found for these Figma properties:
      // "showOverlineText": figma.boolean('showOverlineText?'),
      // "showTitleText": figma.boolean('showTitleText?'),
      // "showSubtitleText": figma.boolean('showSubtitleText?'),
      // "showMetadataText": figma.boolean('showMetadataText?'),
      // "showBodyContent": figma.boolean('showBodyContent?'),
      // "showButtons": figma.boolean('showButtons?'),
      // "showDecorativeBorder": figma.boolean('showDecorativeBorder?'),
      // "showVisualElement": figma.boolean('showVisualElement?'),
      // "titleSlotElement": figma.instance('↪️ titleSlotElement'),
      // "showTitleSlot": figma.boolean('showTitleSlot?'),
      // "state": figma.enum('state', {
      //   "default": "default",
      //   "hover": "hover",
      //   "pressed": "pressed",
      //   "-": "-"
      // }),
      // "visualElementType": figma.enum('visualElementType', {
      //   "image": "image",
      //   "icon": "icon"
      // })
    },
    example: (props) => (
      <Index
        square={props.square}
        image={props.image}
        visualElementType={/* TODO */}
        imagePosition={props.imagePosition}
        imagePadding={props.imagePadding}
        sdsType={props.sdsType}
        titleText={props.titleText}
        boundingBox={props.boundingBox}
        decorativeBorder={props.decorativeBorder}
      />
    ),
  }
);
