import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=387%3A14",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      sdsStyle: figma.enum("sdsStyle", {
        minimal: "minimal",
        tag: "tag",
      }),
    },
    example: (props) => <Index sdsStyle={props.sdsStyle} />,
  }
);
