import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8895%3A46442",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      intent: figma.enum("intent", {
        default: "default",
        negative: "negative",
        notice: "notice",
      }),
      sdsStyle: figma.enum("sdsStyle", {
        rounded: "rounded",
        square: "square",
      }),
      // No matching props could be found for these Figma properties:
      // "showIntentMessage": figma.boolean('showIntentMessage?'),
      // "sdsStage": figma.enum('sdsStage', {
      //   "default": "default",
      //   "userInput": "userinput"
      // })
    },
    example: (props) => (
      <Index
        disabled={props.disabled}
        variant="outlined"
        label="Search Label"
        id="search-example"
        intent={props.intent}
        sdsStyle={props.sdsStyle}
      />
    ),
  }
);
