import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8793%3A19098",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      intent: figma.enum("intent", {
        default: "default",
        negative: "negative",
        notice: "notice",
      }),
      disabled: figma.enum("state", {
        disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showLabelText": figma.boolean('showLabelText?'),
      // "showCaptionText": figma.boolean('showCaptionText?'),
      // "showIntentMessage": figma.boolean('showIntentMessage?'),
      // "sdsStage": figma.enum('sdsStage', {
      //   "selected": "selected",
      //   "unselected": "unselected"
      // })
    },
    example: (props) => (
      <Index intent={props.intent} disabled={props.disabled} />
    ),
  }
);
