import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8784%3A18915",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      intent: figma.enum("intent", {
        default: "default",
        negative: "negative",
        notice: "notice",
      }),
      stage: figma.enum("sdsStage", {
        indeterminate: "indeterminate",
      }),
      disabled: figma.enum("state", {
        disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showCaptionText": figma.boolean('showCaptionText?'),
      // "showLabelText": figma.boolean('showLabelText?'),
      // "showIntentMessage": figma.boolean('showIntentMessage?')
    },
    example: (props) => (
      <Index
        intent={props.intent}
        stage={props.stage}
        disabled={props.disabled}
      />
    ),
  }
);
