blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: mailto:security@chanzuckerberg.com
    about: Please responsibly disclose security issues by emailing us at security@chanzuckerberg.com.
