import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=14517%3A10035",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      position: figma.enum("position", {
        left: "left",
        right: "right",
      }),
      // No matching props could be found for these Figma properties:
      // "panelContent": figma.instance('panelContent'),
      // "headerContent": figma.instance('headerContent'),
      // "sdsType": figma.enum('sdsType', {
      //   "basic": "basic",
      //   "overlay": "overlay"
      // })
    },
    example: (props) => <Index sdsType="basic" position={props.position} />,
  }
);
