import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8945%3A10256",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.instance("↪️ slotContent"),
      buttonPosition: figma.enum("buttonPosition", {
        left: "left",
        right: "right",
      }),
      dismissed: figma.boolean("showDismissButton?"),
      intent: figma.enum("intent", {
        info: "info",
        negative: "negative",
        positive: "positive",
        notice: "notice",
      }),
      // No matching props could be found for these Figma properties:
      // "showDismissButton": figma.boolean('showDismissButton?'),
      // "slotContent": figma.instance('↪️ slotContent'),
      // "showActionButton": figma.boolean('showActionButton?'),
      // "showContentSlot": figma.boolean('showContentSlot?')
    },
    example: (props) => (
      <Index
        icon={props.icon}
        buttonPosition={props.buttonPosition}
        dismissed={props.dismissed}
        slideDirection={/* TODO */}
        intent={props.intent}
      />
    ),
  }
);
