import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=5618%3A13366",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      default: figma.enum("state", {
        default: true,
      }),
      hideSortIcon: figma.boolean("showSortIcon?"),
      horizontalAlign: figma.enum("horizontalAlignment", {
        left: "left",
        center: "center",
        right: "right",
      }),
      hover: figma.enum("state", {
        hover: true,
      }),
      direction: figma.enum("sortDirection", {
        ascending: "asc",
        descending: "desc",
      }),
      // No matching props could be found for these Figma properties:
      // "showSortIcon": figma.boolean('showSortIcon?'),
      // "sdsStage": figma.enum('sdsStage', {
      //   "sorted": "sorted",
      //   "unsorted": "unsorted"
      // }),
      // "textWrap": figma.boolean('textWrap?')
    },
    example: (props) => (
      <Index
        default={props.default}
        hideSortIcon={props.hideSortIcon}
        horizontalAlign={props.horizontalAlign}
        hover={props.hover}
        direction={props.direction}
      >
        Header Text
      </Index>
    ),
  }
);
