import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=3395%3A61013",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      ordered: figma.enum("sdsStyle", {
        ordered: true,
      }),
      // No matching props could be found for these Figma properties:
      // "size": figma.enum('size', {
      //   "fontXxxs": "fontxxxs",
      //   "fontXxs": "fontxxs",
      //   "fontXs": "fontxs",
      //   "fontS": "fonts",
      //   "fontM": "fontm",
      //   "fontL": "fontl"
      // })
    },
    example: (props) => <Index ordered={props.ordered} />,
  }
);
