import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8715%3A15398",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.enum("state (x icon)", {
        hover: "House",
      }),
      dismissed: figma.boolean("dismissible?"),
      dismissible: figma.boolean("dismissible?"),
      intent: figma.enum("intent", {
        info: "info",
        negative: "negative",
        notice: "notice",
        positive: "positive",
      }),
      sdsType: figma.enum("sdsType", {
        primary: "primary",
        secondary: "secondary",
      }),
      // No matching props could be found for these Figma properties:
      // "dismissible": figma.boolean('dismissible?'),
      // "showContentSlot": figma.boolean('showContentSlot?'),
      // "slotContent": figma.instance('↪️ slotContent')
    },
    example: (props) => (
      <Index
        icon={props.icon}
        dismissed={props.dismissed}
        dismissible={props.dismissible}
        intent={props.intent}
        sdsType={props.sdsType}
      />
    ),
  }
);
