import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=9088%3A17404",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      underlined: figma.boolean("showUnderline?"),
      // No matching props could be found for these Figma properties:
      // "tab": figma.enum('tab ', {
      //   "2 tabs": "2-tabs",
      //   "3 tabs": "3-tabs",
      //   "4 tabs": "4-tabs",
      //   "5 tabs": "5-tabs"
      // }),
      // "size": figma.enum('size', {
      //   "s": "s",
      //   "l": "l"
      // }),
      // "activeTab": figma.enum('activeTab', {
      //   "first": "first",
      //   "second": "second",
      //   "third": "third",
      //   "fourth": "fourth",
      //   "fifth": "fifth"
      // }),
      // "hoveredTab": figma.enum('hoveredTab', {
      //   "first": "first",
      //   "second": "second",
      //   "third": "third",
      //   "fourth": "fourth",
      //   "fifth": "fifth",
      //   "-": "-"
      // }),
      // "disabled": figma.boolean('disabled?')
    },
    example: (props) => <Index underlined={props.underlined} />,
  }
);
