import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=9021%3A26589",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      horizontalAlign: figma.enum("horizontalAlignment", {
        left: "left",
        right: "right",
      }),
      verticalAlign: figma.enum("verticalAlignment", {
        top: "top",
        center: "center",
        bottom: "bottom",
      }),
      iconVerticalAlign: figma.enum("verticalAlignment", {
        top: "top",
        center: "center",
        bottom: "bottom",
      }),
      icon: figma.instance("↪️ slotContent"),
      // No matching props could be found for these Figma properties:
      // "showSecondaryText": figma.boolean('showSecondaryText?'),
      // "showTertiaryText": figma.boolean('showTertiaryText?'),
      // "slotContent": figma.instance('↪️ slotContent'),
      // "textWrap": figma.boolean('textWrap?'),
      // "componentSlotPosition": figma.enum('componentSlotPosition', {
      //   "below": "below",
      //   "beside": "beside",
      //   "none": "none"
      // })
    },
    example: (props) => (
      <Index
        horizontalAlign={props.horizontalAlign}
        verticalAlign={props.verticalAlign}
        iconVerticalAlign={props.iconVerticalAlign}
        primaryText={/* TODO */}
        icon={props.icon}
      />
    ),
  }
);
