import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=5579%3A12367",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      horizontalAlign: figma.enum("horizontalAlignment", {
        left: "left",
        center: "center",
        right: "right",
      }),
      verticalAlign: figma.enum("verticalAlignment", {
        center: "center",
        top: "top",
        bottom: "bottom",
      }),
      // No matching props could be found for these Figma properties:
      // "slotContent": figma.instance('slotContent')
    },
    example: (props) => (
      <Index
        horizontalAlign={props.horizontalAlign}
        verticalAlign={props.verticalAlign}
      />
    ),
  }
);
