import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=14374%3A11408",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      hasInvertedStyle: figma.boolean("hasInvertedStyle?"),
      primaryNavPosition: figma.enum("primaryNavPosition", {
        left: "left",
        right: "right",
      }),
      showSearch: figma.boolean("showSecondaryNav?"),
      // No matching props could be found for these Figma properties:
      // "showSecondaryNav": figma.boolean('showSecondaryNav?'),
      // "showButtons": figma.boolean('showButtons?'),
      // "showInputSearch": figma.boolean('showInputSearch?'),
      // "showPrimaryNav": figma.boolean('showPrimaryNav?'),
      // "showIconButton": figma.boolean('showIconButton?'),
      // "showScrollbar": figma.boolean('showScrollbar?'),
      // "sdsType": figma.enum('sdsType', {
      //   "wide": "wide",
      //   "narrow": "narrow"
      // }),
      // "expanded": figma.enum('expanded?', {
      //   "false": "false",
      //   "true": "true",
      //   "-": "-"
      // }),
      // "showDropShadow": figma.enum('showDropShadow?', {
      //   "-": "-",
      //   "false": "false",
      //   "true": "true"
      // })
    },
    example: (props) => (
      <Index
        title={/* TODO */}
        hasInvertedStyle={props.hasInvertedStyle}
        primaryNavPosition={props.primaryNavPosition}
        showSearch={props.showSearch}
      />
    ),
  }
);
