import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=13139%3A33522",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      icon: figma.instance("iconL – primary icon"),
      sdsStage: figma.enum("sdsStage", {
        on: "on",
        "off.": "off",
      }),
      sdsType: figma.enum("sdsType", {
        primary: "primary",
        secondary: "secondary",
      }),
      // No matching props could be found for these Figma properties:
      // "iconLPrimaryIcon": figma.instance('iconL – primary icon'),
      // "iconMPrimaryIcon": figma.instance('iconM – primary icon'),
      // "iconSPrimaryIcon": figma.instance('iconS – primary icon'),
      // "iconLSecondaryIcon": figma.instance('iconL – secondary icon'),
      // "iconMSecondaryIcon": figma.instance('iconM – secondary icon'),
      // "iconSSecondaryIcon": figma.instance('iconS – secondary icon'),
      // "size": figma.enum('size', {
      //   "l": "l",
      //   "m": "m",
      //   "s": "s"
      // })
    },
    example: (props) => (
      <Index
        disabled={props.disabled}
        icon={props.icon}
        sdsStage={props.sdsStage}
        sdsType={props.sdsType}
      />
    ),
  }
);
