import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8989%3A13218",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      search: figma.boolean("showSearch?"),
      isMultiColumn: figma.enum("sdsStyle", {
        multiColumn: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showScrollbars": figma.boolean('showScrollbars?'),
      // "showSectionNames": figma.boolean('showSectionNames?'),
      // "showChevrons": figma.boolean('showChevrons?'),
      // "showApplyButtons": figma.boolean('showApplyButtons?'),
      // "section": figma.enum('section ', {
      //   "1 section": "1-section",
      //   "2 sections": "2-sections",
      //   "3 sections": "3-sections"
      // }),
      // "showTitle": figma.boolean('showTitle?')
    },
    example: (props) => (
      <Index
        options={[]}
        search={props.search}
        anchorEl={null}
        isMultiColumn={props.isMultiColumn}
      />
    ),
  }
);
