import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=6867%3A25911",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      sdsStyle: figma.enum("sdsStyle", {
        rounded: "round",
        square: "square",
      }),
      // No matching props could be found for these Figma properties:
      // "pageQuantity": figma.enum('pageQuantity', {
      //   "2 pages": "2-pages",
      //   "3 pages": "3-pages",
      //   "4 pages": "4-pages",
      //   "5 pages": "5-pages",
      //   "6 pages": "6-pages",
      //   "7+ pages": "7--pages"
      // }),
      // "activePosition": figma.enum('activePosition', {
      //   "first": "first",
      //   "second": "second",
      //   "third": "third",
      //   "fourth": "fourth",
      //   "fifth": "fifth",
      //   "sixth": "sixth",
      //   "seventh": "seventh"
      // }),
      // "hoveredPosition": figma.enum('hoveredPosition', {
      //   "-": "-",
      //   "previous": "previous",
      //   "first": "first",
      //   "second": "second",
      //   "third": "third",
      //   "fourth": "fourth",
      //   "fifth": "fifth",
      //   "sixth": "sixth",
      //   "seventh": "seventh",
      //   "next": "next"
      // })
    },
    example: (props) => (
      <Index
        sdsStyle={props.sdsStyle}
        onPageChange={/* TODO */}
        onNextPage={/* TODO */}
        onPreviousPage={/* TODO */}
        totalCount={/* TODO */}
        currentPage={/* TODO */}
        pageSize={/* TODO */}
      />
    ),
  }
);
