import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=3757%3A63685",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      inverted: figma.boolean("hasInvertedStyle?"),
      hasInvertedStyle: figma.boolean("hasInvertedStyle?"),
      open: figma.enum("placement", {
        topEnd: true,
      }),
      placement: figma.enum("placement", {
        left: "left",
        right: "right",
        bottomEnd: "bottom-end",
        bottomStart: "bottom-start",
        bottom: "bottom",
        leftEnd: "left-end",
        leftStart: "left-start",
        rightEnd: "right-end",
        rightStart: "right-start",
        topEnd: "top-end",
        topStart: "top-start",
        top: "top",
      }),
      slots: figma.instance("↪️ slotContent"),
      // No matching props could be found for these Figma properties:
      // "showCaption": figma.boolean('showCaption?'),
      // "showSlot": figma.boolean('showSlot?'),
      // "slotContent": figma.instance('↪️ slotContent'),
      // "sdsType": figma.enum('sdsType', {
      //   "long": "long",
      //   "short": "short"
      // })
    },
    example: (props) => (
      <Index
        title={/* TODO */}
        inverted={props.inverted}
        hasInvertedStyle={props.hasInvertedStyle}
        open={props.open}
        placement={props.placement}
        slots={props.slots}
      />
    ),
  }
);
