import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=14086%3A9644",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      inverted: figma.boolean("hasInvertedStyle?"),
      hasInvertedStyle: figma.boolean("hasInvertedStyle?"),
      indicator: figma.boolean("showIndicator?"),
      // No matching props could be found for these Figma properties:
      // "showIndicator": figma.boolean('showIndicator?')
    },
    example: (props) => (
      <Index
        title={/* TODO */}
        inverted={props.inverted}
        hasInvertedStyle={props.hasInvertedStyle}
        indicator={props.indicator}
      />
    ),
  }
);
