import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=6432%3A14593",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showTickMarks": figma.boolean('showTickMarks?'),
      // "showHandleValue": figma.boolean('showHandleValue?'),
      // "doubleSided": figma.boolean('doubleSided?'),
      // "upperHandle": figma.enum('upperHandle', {
      //   "0%": "0-",
      //   "10%": "10-",
      //   "20%": "20-",
      //   "30%": "30-",
      //   "40%": "40-",
      //   "50%": "50-",
      //   "60%": "60-",
      //   "70%": "70-",
      //   "80%": "80-",
      //   "90%": "90-",
      //   "100%": "100-"
      // }),
      // "lowerHandle": figma.enum('lowerHandle', {
      //   "0%": "0-",
      //   "10%": "10-",
      //   "20%": "20-",
      //   "30%": "30-",
      //   "40%": "40-",
      //   "50%": "50-",
      //   "60%": "60-",
      //   "70%": "70-",
      //   "80%": "80-",
      //   "90%": "90-",
      //   "100%": "100-"
      // })
    },
    example: (props) => <Index disabled={props.disabled} />,
  }
);
