import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=3258%3A61211",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      showSectionHeader: figma.boolean("showSectionNames?"),
      // No matching props could be found for these Figma properties:
      // "showSectionNames": figma.boolean('showSectionNames?'),
      // "section": figma.enum('section ', {
      //   "1 section": "1-section",
      //   "2 sections": "2-sections",
      //   "3 sections": "3-sections"
      // })
    },
    example: (props) => <Index showSectionHeader={props.showSectionHeader} />,
  }
);
