import { PaletteMode } from "@mui/material";
import { AppTheme, SDSPalette, SDSThemeOptions } from "./types";
import { Breakpoints } from "./constants/breakpoints";
import { addOpacityToHex } from "./utils/opacity";

export const SDSPaletteLight = (appTheme: AppTheme): SDSPalette => {
  return {
    accent: {
      border: appTheme.colors.indigo[500],
      borderFocus: appTheme.colors.indigo[500],
      borderHover: appTheme.colors.indigo[600],
      borderOpen: appTheme.colors.indigo[500],
      borderPressed: appTheme.colors.indigo[700],
      borderSelected: appTheme.colors.indigo[500],
      fillHover: appTheme.colors.indigo[600],
      fillPressed: appTheme.colors.indigo[700],
      fillPrimary: appTheme.colors.indigo[500],
      fillInteraction: appTheme.colors.indigo[600],
      foreground: appTheme.colors.indigo[500],
      foregroundOnDark: appTheme.colors.indigo[400],
      foregroundInteraction: appTheme.colors.indigo[600],
      foregroundInteractionOnDark: appTheme.colors.indigo[300],
      foregroundPressed: appTheme.colors.indigo[700],
      forgroundPressedOnDark: appTheme.colors.indigo[200],
      foregroundActive: appTheme.colors.indigo[500],
      ornament: appTheme.colors.indigo[500],
      ornamentFocus: appTheme.colors.indigo[500],
      ornamentHover: appTheme.colors.indigo[600],
      ornamentOpen: appTheme.colors.indigo[500],
      ornamentPressed: appTheme.colors.indigo[700],
      ornamentSelected: appTheme.colors.indigo[500],
      surfacePrimary: appTheme.colors.indigo[500],
      surfaceSecondary: appTheme.colors.indigo[100],
      surfaceSecondaryOnDark: appTheme.colors.indigo[800],
      textAction: appTheme.colors.indigo[500],
      textActionHover: appTheme.colors.indigo[600],
      textActionPressed: appTheme.colors.indigo[700],
    },
    base: {
      backgroundPrimary: appTheme.colors.gray[50]!,
      backgroundPrimaryDark: appTheme.colors.gray[900]!,
      backgroundPrimaryInverse: appTheme.colors.gray[900]!,
      backgroundSecondary: addOpacityToHex(appTheme.colors.gray[100], 40),
      backgroundSecondaryDark: addOpacityToHex(appTheme.colors.gray[700], 62),
      backgroundSecondaryInverse: appTheme.colors.gray[700],
      backgroundTertiary: appTheme.colors.gray[100],
      borderOnFill: appTheme.colors.gray[50]!,
      borderPrimary: appTheme.colors.gray[600],
      borderPrimaryDisabled: appTheme.colors.gray[300],
      borderPrimaryDisabledOnDark: appTheme.colors.gray[600],
      borderPrimaryDisabledInverse: appTheme.colors.gray[600],
      borderPrimaryInteraction: appTheme.colors.gray[900]!,
      borderPrimaryInteractionOnDark: appTheme.colors.gray[50]!,
      borderPrimaryHoverInverse: appTheme.colors.gray[50]!,
      borderPrimaryOnDark: appTheme.colors.gray[300],
      borderPrimaryInverse: appTheme.colors.gray[300],
      borderPrimaryPressedInverse: appTheme.colors.gray[50]!,
      borderSecondary: appTheme.colors.gray[300],
      borderSecondaryOnDark: appTheme.colors.gray[600],
      divider: appTheme.colors.gray[200],
      dividerOnDark: appTheme.colors.gray[700],
      dividerInverse: appTheme.colors.gray[700],
      fillDisabled: appTheme.colors.gray[100],
      fillPrimaryInteraction: addOpacityToHex(appTheme.colors.gray[300], 20),
      fillPrimaryInteractionOnDark: addOpacityToHex(
        appTheme.colors.gray[300],
        20
      ),
      fillHoverInverse: addOpacityToHex(appTheme.colors.gray[300], 20),
      fillOpenInverse: addOpacityToHex(appTheme.colors.gray[300], 34),
      fillPrimaryPressed: addOpacityToHex(appTheme.colors.gray[300], 30),
      fillPrimaryPressedOnDark: addOpacityToHex(appTheme.colors.gray[300], 24),
      fillPressedInverse: addOpacityToHex(appTheme.colors.gray[300], 34),
      fillPrimary: appTheme.colors.gray[50]!,
      fillSelected: appTheme.colors.gray[900]!,
      fillSecondary: appTheme.colors.gray[200],
      fillSecondaryInteraction: addOpacityToHex(appTheme.colors.gray[400], 34),
      fillSecondaryPressed: addOpacityToHex(appTheme.colors.gray[400], 60),
      fillSecondaryOnDark: appTheme.colors.gray[700],
      fillSecondaryInteractionOnDark: addOpacityToHex(
        appTheme.colors.gray[400],
        32
      ),
      fillSecondaryPressedOnDark: addOpacityToHex(
        appTheme.colors.gray[400],
        46
      ),
      fillDisabledOnDark: appTheme.colors.gray[700],
      ornamentDisabled: appTheme.colors.gray[300],
      ornamentDisabledOnDark: appTheme.colors.gray[600],
      ornamentDisabledInverse: appTheme.colors.gray[600],
      ornamentOnFill: appTheme.colors.gray[50]!,
      ornamentPrimary: appTheme.colors.gray[900]!,
      ornamentPrimaryOnDark: appTheme.colors.gray[50]!,
      ornamentPrimaryInverse: appTheme.colors.gray[50]!,
      ornamentSecondary: appTheme.colors.gray[600],
      ornamentSecondaryInteraction: appTheme.colors.gray[900]!,
      ornamentSecondaryInteractionOnDark: appTheme.colors.gray[50]!,
      ornamentSecondaryHoverInverse: appTheme.colors.gray[50]!,
      ornamentSecondaryOnDark: appTheme.colors.gray[300],
      ornamentSecondaryInverse: appTheme.colors.gray[300],
      ornamentSecondaryPressedInverse: appTheme.colors.gray[50]!,
      surfacePrimary: appTheme.colors.gray[50]!,
      surfaceSecondary: addOpacityToHex(appTheme.colors.gray[300], 20),
      surfacePrimaryDark: appTheme.colors.gray[900]!,
      surfaceInverse: appTheme.colors.gray[900]!,
      textDisabled: appTheme.colors.gray[300],
      textDisabledOnDark: appTheme.colors.gray[600],
      textDisabledInverse: appTheme.colors.gray[600],
      textOnFill: appTheme.colors.gray[50]!,
      textPrimary: appTheme.colors.gray[900]!,
      textPrimaryOnDark: appTheme.colors.gray[50]!,
      textPrimaryInverse: appTheme.colors.gray[50]!,
      textSecondary: appTheme.colors.gray[600],
      textSecondaryOnDark: appTheme.colors.gray[300],
      textSecondaryInverse: appTheme.colors.gray[300],
      textTertiary: appTheme.colors.gray[400],
      textTertiaryOnDark: appTheme.colors.gray[500],
      textTertiaryInverse: appTheme.colors.gray[500],
    },
    beta: {
      border: appTheme.colors.purple[600],
      fillHover: appTheme.colors.purple[600],
      fillPressed: appTheme.colors.purple[700],
      fillPrimary: appTheme.colors.purple[500],
      fillSecondary: appTheme.colors.purple[100],
      ornament: appTheme.colors.purple[600],
      surfacePrimary: appTheme.colors.purple[500],
      surfaceSecondary: appTheme.colors.purple[100],
      text: appTheme.colors.purple[600],
      fillInteraction: appTheme.colors.purple[600],
      foreground: appTheme.colors.purple[600],
      foregroundOnDark: appTheme.colors.purple[300],
      foregroundInteraction: appTheme.colors.purple[700],
      foregroundInteractionOnDark: appTheme.colors.purple[200],
      foregroundPressed: appTheme.colors.purple[800],
      forgroundPressedOnDark: appTheme.colors.purple[100],
    },
    info: {
      border: appTheme.colors.blue[600],
      fillHover: appTheme.colors.blue[600],
      fillPressed: appTheme.colors.blue[700],
      fillPrimary: appTheme.colors.blue[500],
      fillSecondary: appTheme.colors.blue[100],
      ornament: appTheme.colors.blue[600],
      surfacePrimary: appTheme.colors.blue[500],
      surfaceSecondary: appTheme.colors.blue[100],
      text: appTheme.colors.blue[600],
      fillInteraction: appTheme.colors.blue[600],
      foreground: appTheme.colors.blue[600],
      foregroundOnDark: appTheme.colors.blue[300],
      foregroundInteraction: appTheme.colors.blue[700],
      foregroundInteractionOnDark: appTheme.colors.blue[200],
      foregroundPressed: appTheme.colors.blue[800],
      forgroundPressedOnDark: appTheme.colors.blue[100],
    },
    negative: {
      border: appTheme.colors.red[600],
      fillHover: appTheme.colors.red[600],
      fillPressed: appTheme.colors.red[700],
      fillPrimary: appTheme.colors.red[500],
      fillSecondary: appTheme.colors.red[100],
      ornament: appTheme.colors.red[600],
      surfacePrimary: appTheme.colors.red[500],
      surfaceSecondary: appTheme.colors.red[100],
      text: appTheme.colors.red[600],
      fillInteraction: appTheme.colors.red[600],
      foreground: appTheme.colors.red[600],
      foregroundOnDark: appTheme.colors.red[300],
      foregroundInteraction: appTheme.colors.red[700],
      foregroundInteractionOnDark: appTheme.colors.red[200],
      foregroundPressed: appTheme.colors.red[800],
      forgroundPressedOnDark: appTheme.colors.red[100],
    },
    neutral: {
      border: appTheme.colors.gray[700],
      fillHover: appTheme.colors.gray[700],
      fillPressed: appTheme.colors.gray[800],
      fillPrimary: appTheme.colors.gray[600],
      fillSecondary: appTheme.colors.gray[200],
      ornament: appTheme.colors.gray[700],
      surfacePrimary: appTheme.colors.gray[600],
      surfaceSecondary: appTheme.colors.gray[200],
      text: appTheme.colors.gray[700],
      fillInteraction: appTheme.colors.gray[700],
      foreground: appTheme.colors.gray[700],
      foregroundOnDark: appTheme.colors.gray[300],
      foregroundInteraction: appTheme.colors.gray[800],
      foregroundInteractionOnDark: appTheme.colors.gray[200],
      foregroundPressed: appTheme.colors.gray[900]!,
      forgroundPressedOnDark: appTheme.colors.gray[100],
    },
    notice: {
      border: appTheme.colors.yellow[600],
      fillHover: appTheme.colors.yellow[600],
      fillPressed: appTheme.colors.yellow[700],
      fillPrimary: appTheme.colors.yellow[500],
      fillSecondary: appTheme.colors.yellow[100],
      ornament: appTheme.colors.yellow[600],
      surfacePrimary: appTheme.colors.yellow[500],
      surfaceSecondary: appTheme.colors.yellow[100],
      text: appTheme.colors.yellow[600],
      fillInteraction: appTheme.colors.yellow[600],
      foreground: appTheme.colors.yellow[600],
      foregroundOnDark: appTheme.colors.yellow[300],
      foregroundInteraction: appTheme.colors.yellow[700],
      foregroundInteractionOnDark: appTheme.colors.yellow[200],
      foregroundPressed: appTheme.colors.yellow[800],
      forgroundPressedOnDark: appTheme.colors.yellow[100],
    },
    positive: {
      border: appTheme.colors.green[600],
      fillHover: appTheme.colors.green[600],
      fillPressed: appTheme.colors.green[700],
      fillPrimary: appTheme.colors.green[500],
      fillSecondary: appTheme.colors.green[100],
      ornament: appTheme.colors.green[600],
      surfacePrimary: appTheme.colors.green[500],
      surfaceSecondary: appTheme.colors.green[100],
      text: appTheme.colors.green[600],
      fillInteraction: appTheme.colors.green[600],
      foreground: appTheme.colors.green[600],
      foregroundOnDark: appTheme.colors.green[300],
      foregroundInteraction: appTheme.colors.green[700],
      foregroundInteractionOnDark: appTheme.colors.green[200],
      foregroundPressed: appTheme.colors.green[800],
      forgroundPressedOnDark: appTheme.colors.green[100],
    },
  };
};

export const SDSPaletteDark = (appTheme: AppTheme): SDSPalette => {
  return {
    accent: {
      border: appTheme.colors.indigo[600],
      borderFocus: appTheme.colors.indigo[600],
      borderHover: appTheme.colors.indigo[700],
      borderOpen: appTheme.colors.indigo[600],
      borderPressed: appTheme.colors.indigo[800],
      borderSelected: appTheme.colors.indigo[600],
      fillHover: appTheme.colors.indigo[700],
      fillPressed: appTheme.colors.indigo[800],
      fillPrimary: appTheme.colors.indigo[400],
      fillInteraction: appTheme.colors.indigo[700],
      foreground: appTheme.colors.indigo[600],
      foregroundOnDark: appTheme.colors.indigo[600],
      foregroundInteraction: appTheme.colors.indigo[700],
      foregroundInteractionOnDark: appTheme.colors.indigo[700],
      foregroundPressed: appTheme.colors.indigo[800],
      forgroundPressedOnDark: appTheme.colors.indigo[800],
      foregroundActive: appTheme.colors.indigo[600],
      ornament: appTheme.colors.indigo[600],
      ornamentFocus: appTheme.colors.indigo[600],
      ornamentHover: appTheme.colors.indigo[700],
      ornamentOpen: appTheme.colors.indigo[600],
      ornamentPressed: appTheme.colors.indigo[800],
      ornamentSelected: appTheme.colors.indigo[600],
      surfacePrimary: appTheme.colors.indigo[400],
      surfaceSecondary: appTheme.colors.indigo[100],
      surfaceSecondaryOnDark: appTheme.colors.indigo[100],
      textAction: appTheme.colors.indigo[600],
      textActionHover: appTheme.colors.indigo[700],
      textActionPressed: appTheme.colors.indigo[800],
    },
    base: {
      backgroundPrimary: appTheme.colors.gray[75]!,
      backgroundPrimaryDark: appTheme.colors.gray[75]!,
      backgroundPrimaryInverse: appTheme.colors.gray[75]!,
      backgroundSecondary: addOpacityToHex(appTheme.colors.gray[100], 60),
      backgroundSecondaryDark: addOpacityToHex(appTheme.colors.gray[100], 60),
      backgroundSecondaryInverse: addOpacityToHex(
        appTheme.colors.gray[100],
        60
      ),
      backgroundTertiary: appTheme.colors.gray[100],
      borderOnFill: appTheme.colors.gray[900]!,
      borderPrimary: appTheme.colors.gray[600],
      borderPrimaryDisabled: appTheme.colors.gray[300],
      borderPrimaryDisabledOnDark: appTheme.colors.gray[300],
      borderPrimaryDisabledInverse: appTheme.colors.gray[300],
      borderPrimaryInteraction: appTheme.colors.gray[900]!,
      borderPrimaryInteractionOnDark: appTheme.colors.gray[900]!,
      borderPrimaryHoverInverse: appTheme.colors.gray[900]!,
      borderPrimaryOnDark: appTheme.colors.gray[600],
      borderPrimaryInverse: appTheme.colors.gray[600],
      borderPrimaryPressedInverse: appTheme.colors.gray[900]!,
      borderSecondary: appTheme.colors.gray[300],
      borderSecondaryOnDark: appTheme.colors.gray[300],
      divider: appTheme.colors.gray[200],
      dividerOnDark: appTheme.colors.gray[200],
      dividerInverse: appTheme.colors.gray[200],
      fillDisabled: appTheme.colors.gray[100],
      fillPrimaryInteraction: addOpacityToHex(appTheme.colors.gray[300], 32),
      fillPrimaryInteractionOnDark: addOpacityToHex(
        appTheme.colors.gray[300],
        32
      ),
      fillHoverInverse: addOpacityToHex(appTheme.colors.gray[300], 32),
      fillOpenInverse: addOpacityToHex(appTheme.colors.gray[300], 32),
      fillPrimaryPressed: addOpacityToHex(appTheme.colors.gray[300], 40),
      fillPrimaryPressedOnDark: addOpacityToHex(appTheme.colors.gray[300], 40),
      fillPressedInverse: addOpacityToHex(appTheme.colors.gray[300], 32),
      fillPrimary: appTheme.colors.gray[100],
      fillSelected: appTheme.colors.gray[900]!,
      fillSecondary: appTheme.colors.gray[200],
      fillSecondaryInteraction: addOpacityToHex(appTheme.colors.gray[400], 26),
      fillSecondaryPressed: addOpacityToHex(appTheme.colors.gray[400], 46),
      fillSecondaryOnDark: appTheme.colors.gray[200],
      fillSecondaryInteractionOnDark: addOpacityToHex(
        appTheme.colors.gray[400],
        34
      ),
      fillSecondaryPressedOnDark: addOpacityToHex(
        appTheme.colors.gray[400],
        46
      ),
      fillDisabledOnDark: appTheme.colors.gray[100],
      ornamentDisabled: appTheme.colors.gray[300],
      ornamentDisabledOnDark: appTheme.colors.gray[300],
      ornamentDisabledInverse: appTheme.colors.gray[300],
      ornamentOnFill: appTheme.colors.gray[900]!,
      ornamentPrimary: appTheme.colors.gray[900]!,
      ornamentPrimaryOnDark: appTheme.colors.gray[900]!,
      ornamentPrimaryInverse: appTheme.colors.gray[50]!,
      ornamentSecondary: appTheme.colors.gray[600],
      ornamentSecondaryInteraction: appTheme.colors.gray[900]!,
      ornamentSecondaryInteractionOnDark: appTheme.colors.gray[900]!,
      ornamentSecondaryHoverInverse: appTheme.colors.gray[900]!,
      ornamentSecondaryOnDark: appTheme.colors.gray[600],
      ornamentSecondaryInverse: appTheme.colors.gray[600],
      ornamentSecondaryPressedInverse: appTheme.colors.gray[900]!,
      surfacePrimary: appTheme.colors.gray[100],
      surfaceSecondary: addOpacityToHex(appTheme.colors.gray[300], 32),
      surfacePrimaryDark: appTheme.colors.gray[100],
      surfaceInverse: appTheme.colors.gray[100],
      textDisabled: appTheme.colors.gray[300],
      textDisabledOnDark: appTheme.colors.gray[300],
      textDisabledInverse: appTheme.colors.gray[300],
      textOnFill: appTheme.colors.gray[900]!,
      textPrimary: appTheme.colors.gray[900]!,
      textPrimaryOnDark: appTheme.colors.gray[900]!,
      textPrimaryInverse: appTheme.colors.gray[50]!,
      textSecondary: appTheme.colors.gray[600],
      textSecondaryOnDark: appTheme.colors.gray[600],
      textSecondaryInverse: appTheme.colors.gray[600],
      textTertiary: appTheme.colors.gray[400],
      textTertiaryOnDark: appTheme.colors.gray[400],
      textTertiaryInverse: appTheme.colors.gray[400],
    },
    beta: {
      border: appTheme.colors.purple[600],
      fillHover: appTheme.colors.purple[700],
      fillPressed: appTheme.colors.purple[800],
      fillPrimary: appTheme.colors.purple[400],
      fillSecondary: appTheme.colors.purple[100],
      ornament: appTheme.colors.purple[600],
      surfacePrimary: appTheme.colors.purple[400],
      surfaceSecondary: appTheme.colors.purple[100],
      text: appTheme.colors.purple[600],
      fillInteraction: appTheme.colors.purple[700],
      foreground: appTheme.colors.purple[600],
      foregroundOnDark: appTheme.colors.purple[600],
      foregroundInteraction: appTheme.colors.purple[700],
      foregroundInteractionOnDark: appTheme.colors.purple[700],
      foregroundPressed: appTheme.colors.purple[800],
      forgroundPressedOnDark: appTheme.colors.purple[800],
    },
    info: {
      border: appTheme.colors.blue[600],
      fillHover: appTheme.colors.blue[700],
      fillPressed: appTheme.colors.blue[800],
      fillPrimary: appTheme.colors.blue[400],
      fillSecondary: appTheme.colors.blue[100],
      ornament: appTheme.colors.blue[600],
      surfacePrimary: appTheme.colors.blue[400],
      surfaceSecondary: appTheme.colors.blue[100],
      text: appTheme.colors.blue[600],
      fillInteraction: appTheme.colors.blue[700],
      foreground: appTheme.colors.blue[600],
      foregroundOnDark: appTheme.colors.blue[600],
      foregroundInteraction: appTheme.colors.blue[700],
      foregroundInteractionOnDark: appTheme.colors.blue[700],
      foregroundPressed: appTheme.colors.blue[800],
      forgroundPressedOnDark: appTheme.colors.blue[800],
    },
    negative: {
      border: appTheme.colors.red[600],
      fillHover: appTheme.colors.red[700],
      fillPressed: appTheme.colors.red[800],
      fillPrimary: appTheme.colors.red[400],
      fillSecondary: appTheme.colors.red[100],
      ornament: appTheme.colors.red[600],
      surfacePrimary: appTheme.colors.red[400],
      surfaceSecondary: appTheme.colors.red[100],
      text: appTheme.colors.red[600],
      fillInteraction: appTheme.colors.red[700],
      foreground: appTheme.colors.red[600],
      foregroundOnDark: appTheme.colors.red[600],
      foregroundInteraction: appTheme.colors.red[700],
      foregroundInteractionOnDark: appTheme.colors.red[700],
      foregroundPressed: appTheme.colors.red[800],
      forgroundPressedOnDark: appTheme.colors.red[800],
    },
    neutral: {
      border: appTheme.colors.gray[700],
      fillHover: appTheme.colors.gray[600],
      fillPressed: appTheme.colors.gray[700],
      fillPrimary: appTheme.colors.gray[400],
      fillSecondary: appTheme.colors.gray[200],
      ornament: appTheme.colors.gray[700],
      surfacePrimary: appTheme.colors.gray[400],
      surfaceSecondary: appTheme.colors.gray[200],
      text: appTheme.colors.gray[700],
      fillInteraction: appTheme.colors.gray[600],
      foreground: appTheme.colors.gray[700],
      foregroundOnDark: appTheme.colors.gray[700],
      foregroundInteraction: appTheme.colors.gray[800],
      foregroundInteractionOnDark: appTheme.colors.gray[800],
      foregroundPressed: appTheme.colors.gray[900]!,
      forgroundPressedOnDark: appTheme.colors.gray[900]!,
    },
    notice: {
      border: appTheme.colors.yellow[600],
      fillHover: appTheme.colors.yellow[700],
      fillPressed: appTheme.colors.yellow[800],
      fillPrimary: appTheme.colors.yellow[400],
      fillSecondary: appTheme.colors.yellow[100],
      ornament: appTheme.colors.yellow[600],
      surfacePrimary: appTheme.colors.yellow[400],
      surfaceSecondary: appTheme.colors.yellow[100],
      text: appTheme.colors.yellow[600],
      fillInteraction: appTheme.colors.yellow[700],
      foreground: appTheme.colors.yellow[600],
      foregroundOnDark: appTheme.colors.yellow[600],
      foregroundInteraction: appTheme.colors.yellow[700],
      foregroundInteractionOnDark: appTheme.colors.yellow[700],
      foregroundPressed: appTheme.colors.yellow[800],
      forgroundPressedOnDark: appTheme.colors.yellow[800],
    },
    positive: {
      border: appTheme.colors.green[600],
      fillHover: appTheme.colors.green[700],
      fillPressed: appTheme.colors.green[800],
      fillPrimary: appTheme.colors.green[400],
      fillSecondary: appTheme.colors.green[100],
      ornament: appTheme.colors.green[600],
      surfacePrimary: appTheme.colors.green[400],
      surfaceSecondary: appTheme.colors.green[100],
      text: appTheme.colors.green[600],
      fillInteraction: appTheme.colors.green[700],
      foreground: appTheme.colors.green[600],
      foregroundOnDark: appTheme.colors.green[600],
      foregroundInteraction: appTheme.colors.green[700],
      foregroundInteractionOnDark: appTheme.colors.green[700],
      foregroundPressed: appTheme.colors.green[800],
      forgroundPressedOnDark: appTheme.colors.green[800],
    },
  };
};

/**
 * This function creates the theme options for the MUI theme provider
 */
export function makeThemeOptions(
  appTheme: AppTheme,
  mode: PaletteMode
): SDSThemeOptions {
  return {
    app: appTheme,
    breakpoints: {
      values: Breakpoints,
    },
    components: {
      MuiButton: {
        defaultProps: {
          disableFocusRipple: true,
          disableRipple: true,
          disableTouchRipple: true,
        },
      },
      MuiButtonBase: {
        defaultProps: {
          disableRipple: true,
          disableTouchRipple: true,
        },
      },
      MuiButtonGroup: {
        defaultProps: {
          disableFocusRipple: true,
          disableRipple: true,
        },
      },
      MuiDrawer: {
        defaultProps: {
          hideBackdrop: true,
        },
      },
      MuiIconButton: {
        defaultProps: {
          disableFocusRipple: true,
          disableRipple: true,
          disableTouchRipple: true,
        },
      },
      MuiLink: {
        defaultProps: {
          underline: "hover",
        },
      },
      MuiTab: {
        defaultProps: {
          disableFocusRipple: true,
          disableRipple: true,
          disableTouchRipple: true,
        },
      },
      MuiToggleButton: {
        defaultProps: {
          disableFocusRipple: true,
          disableRipple: true,
          disableTouchRipple: true,
        },
      },
    },
    palette: {
      action: {
        disabled: appTheme.colors.gray[400],
        disabledBackground: appTheme.colors.gray[300],
      },
      background: {
        default:
          mode === "dark" ? appTheme.colors.gray[75] : appTheme.colors.gray[50],
      },
      divider: appTheme.colors.gray[200],
      error: {
        "100": appTheme.colors.red[100],
        "200": appTheme.colors.red[200],
        "300": appTheme.colors.red[300],
        "400": appTheme.colors.red[400],
        "500": appTheme.colors.red[500],
        "600": appTheme.colors.red[600],
        contrastText: appTheme.colors.gray[50],
        dark: appTheme.colors.red[600],
        light: appTheme.colors.red[200],
        main: appTheme.colors.red[400],
      },
      grey: {
        "100": appTheme.colors.gray[100],
        "200": appTheme.colors.gray[200],
        "300": appTheme.colors.gray[300],
        "400": appTheme.colors.gray[400],
        "500": appTheme.colors.gray[500],
        "600": appTheme.colors.gray[600],
      },
      info: {
        "100": appTheme.colors.blue[100],
        "200": appTheme.colors.blue[200],
        "300": appTheme.colors.blue[300],
        "400": appTheme.colors.blue[400],
        "500": appTheme.colors.blue[500],
        "600": appTheme.colors.blue[600],
        contrastText: appTheme.colors.gray[50],
        dark: appTheme.colors.blue[600],
        light: appTheme.colors.blue[200],
        main: appTheme.colors.blue[400],
      },
      mode: mode,
      primary: {
        "100": appTheme.colors.blue[100],
        "200": appTheme.colors.blue[200],
        "300": appTheme.colors.blue[300],
        "400": appTheme.colors.blue[400],
        "500": appTheme.colors.blue[500],
        "600": appTheme.colors.blue[600],
        contrastText: appTheme.colors.gray[50],
        dark: appTheme.colors.blue[600],
        light: appTheme.colors.blue[200],
        main: appTheme.colors.blue[400],
      },
      sds:
        mode === "dark" ? SDSPaletteDark(appTheme) : SDSPaletteLight(appTheme),
      secondary: {
        "100": appTheme.colors.green[100],
        "200": appTheme.colors.green[200],
        "300": appTheme.colors.green[300],
        "400": appTheme.colors.green[400],
        "500": appTheme.colors.green[500],
        "600": appTheme.colors.green[600],
        contrastText: appTheme.colors.gray[50],
        dark: appTheme.colors.green[600],
        light: appTheme.colors.green[200],
        main: appTheme.colors.green[400],
      },
      success: {
        "100": appTheme.colors.green[100],
        "200": appTheme.colors.green[200],
        "300": appTheme.colors.green[300],
        "400": appTheme.colors.green[400],
        "500": appTheme.colors.green[500],
        "600": appTheme.colors.green[600],
        contrastText: appTheme.colors.gray[50],
        dark: appTheme.colors.green[600],
        light: appTheme.colors.green[200],
        main: appTheme.colors.green[400],
      },
      text: {
        disabled: appTheme.colors.gray[300],
        primary: appTheme.colors.gray[900],
        secondary: appTheme.colors.gray[600],
      },
      warning: {
        "100": appTheme.colors.yellow[100],
        "200": appTheme.colors.yellow[200],
        "300": appTheme.colors.yellow[300],
        "400": appTheme.colors.yellow[400],
        "500": appTheme.colors.yellow[500],
        "600": appTheme.colors.yellow[600],
        contrastText: appTheme.colors.gray[900],
        dark: appTheme.colors.yellow[600],
        light: appTheme.colors.yellow[200],
        main: appTheme.colors.yellow[400],
      },
    },
    shadows: [
      appTheme.shadows.none,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
    ],
    shape: {
      borderRadius: appTheme.corners.m,
    },
    spacing: [
      appTheme.spacing.default,
      appTheme.spacing.xxxs,
      appTheme.spacing.xxs,
      appTheme.spacing.xs,
      appTheme.spacing.s,
      appTheme.spacing.m,
      appTheme.spacing.l,
      appTheme.spacing.xl,
      appTheme.spacing.xxl,
      appTheme.spacing.xxxl,
    ],
    transitions: {
      duration: {
        complex: 200,
        enteringScreen: 20,
        leavingScreen: 10,
        short: 150,
        shorter: 100,
        shortest: 50,
        standard: 200,
      },
      easing: {
        easeIn: "cubic-bezier(0, 0, 0.2, 1)",
        easeInOut: "cubic-bezier(0, 0, 0.2, 1)",
        easeOut: "cubic-bezier(0.0, 0, 0.2, 1)",
        sharp: "cubic-bezier(0, 0.2, 0.6, 1)",
      },
    },
    typography: {
      body1: appTheme.typography.wideStyles.body.regular.xs,
      body2: appTheme.typography.wideStyles.body.regular.xxs,
      button: appTheme.typography.wideStyles.body.regular.xs,
      caption: appTheme.typography.wideStyles.body.regular.xxxs,
      fontFamily: `${appTheme.typography.fontFamily.body}, sans-serif`,
      h1: appTheme.typography.wideStyles.header.semibold.xxl,
      h2: appTheme.typography.wideStyles.header.semibold.xl,
      h3: appTheme.typography.wideStyles.header.semibold.l,
      h4: appTheme.typography.wideStyles.header.semibold.m,
      h5: appTheme.typography.wideStyles.header.semibold.s,
      h6: appTheme.typography.wideStyles.header.semibold.xs,
      overline: appTheme.typography.wideStyles.caps.semibold.xxxs,
      subtitle1: appTheme.typography.wideStyles.body.regular.xs,
      subtitle2: appTheme.typography.wideStyles.header.semibold.xxs,
    },
  };
}
