import { colors } from "@mui/material";
import { AppTheme, SDSThemeOptions } from "./types";

const { common } = colors;

/**
 * This function creates the theme options for the MUI theme provider
 */
export function makeThemeOptions(appTheme: AppTheme): SDSThemeOptions {
  return {
    app: appTheme,
    components: {
      MuiButtonBase: {
        defaultProps: {
          disableRipple: true,
        },
      },
      MuiLink: {
        defaultProps: {
          underline: "hover",
        },
      },
      MuiTab: {
        defaultProps: {
          disableRipple: true,
        },
      },
    },
    palette: {
      action: {
        disabled: appTheme.colors.gray[400],
        disabledBackground: appTheme.colors.gray[300],
      },
      divider: appTheme.colors.gray[200],
      error: {
        "100": appTheme.colors.red[100],
        "200": appTheme.colors.red[200],
        "300": appTheme.colors.red[300],
        "400": appTheme.colors.red[400],
        "500": appTheme.colors.red[500],
        "600": appTheme.colors.red[600],
        contrastText: common.white,
        dark: appTheme.colors.red[600],
        light: appTheme.colors.red[200],
        main: appTheme.colors.red[400],
      },
      grey: {
        "100": appTheme.colors.gray[100],
        "200": appTheme.colors.gray[200],
        "300": appTheme.colors.gray[300],
        "400": appTheme.colors.gray[400],
        "500": appTheme.colors.gray[500],
        "600": appTheme.colors.gray[600],
      },
      info: {
        "100": appTheme.colors.blue[100],
        "200": appTheme.colors.blue[200],
        "300": appTheme.colors.blue[300],
        "400": appTheme.colors.blue[400],
        "500": appTheme.colors.blue[500],
        "600": appTheme.colors.blue[600],
        contrastText: common.white,
        dark: appTheme.colors.blue[600],
        light: appTheme.colors.blue[200],
        main: appTheme.colors.blue[400],
      },
      mode: "light",
      primary: {
        "100": appTheme.colors.blue[100],
        "200": appTheme.colors.blue[200],
        "300": appTheme.colors.blue[300],
        "400": appTheme.colors.blue[400],
        "500": appTheme.colors.blue[500],
        "600": appTheme.colors.blue[600],
        contrastText: common.white,
        dark: appTheme.colors.blue[600],
        light: appTheme.colors.blue[200],
        main: appTheme.colors.blue[400],
      },
      sds: {
        component: {
          accent: {
            border: appTheme.colors.blue[400],
            borderDisabled: appTheme.colors.blue[300],
            borderFocus: appTheme.colors.blue[400],
            borderHover: appTheme.colors.blue[500],
            borderOpen: appTheme.colors.blue[400],
            borderPressed: appTheme.colors.blue[600],
            borderSelected: appTheme.colors.blue[400],
            fill: appTheme.colors.blue[400],
            fillDisabled: appTheme.colors.blue[300],
            fillHover: appTheme.colors.blue[500],
            fillOnFill: appTheme.colors.common.white,
            fillPressed: appTheme.colors.blue[600],
            icon: appTheme.colors.blue[400],
            surface: appTheme.colors.blue[200],
          },
          base: {
            border: appTheme.colors.gray[400],
            borderDisabled: appTheme.colors.gray[300],
            borderHover: appTheme.colors.common.black,
            borderPressed: appTheme.colors.common.black,
            borderTable: appTheme.colors.gray[300],
            divider: appTheme.colors.gray[200],
            fill: appTheme.colors.common.white,
            fillDisabled: appTheme.colors.gray[300],
            fillHover: appTheme.colors.gray[100],
            fillOpen: appTheme.colors.gray[100],
            fillPressed: appTheme.colors.gray[100],
            fillSelected: appTheme.colors.common.black,
            icon: appTheme.colors.gray[500],
            iconDisabled: appTheme.colors.gray[300],
            iconHover: appTheme.colors.common.black,
            iconPressed: appTheme.colors.common.black,
            onFillDisabled: appTheme.colors.gray[400],
            surface: appTheme.colors.common.white,
            surfacePrimary: appTheme.colors.common.white,
            surfaceSecondary: appTheme.colors.gray[100],
            surfaceTertiary: appTheme.colors.gray[200],
          },
          beta: {
            border: appTheme.colors.purple[400],
            fill: appTheme.colors.purple[400],
            fillHover: appTheme.colors.purple[500],
            fillOnFill: appTheme.colors.common.white,
            fillPressed: appTheme.colors.purple[600],
            icon: appTheme.colors.purple[400],
            surface: appTheme.colors.purple[200],
          },
          info: {
            border: appTheme.colors.blue[400],
            fill: appTheme.colors.blue[400],
            fillHover: appTheme.colors.blue[500],
            fillOnFill: appTheme.colors.common.white,
            fillPressed: appTheme.colors.blue[600],
            icon: appTheme.colors.blue[400],
            surface: appTheme.colors.blue[200],
          },
          negative: {
            border: appTheme.colors.red[400],
            fill: appTheme.colors.red[400],
            fillHover: appTheme.colors.red[500],
            fillOnFill: appTheme.colors.common.white,
            fillPressed: appTheme.colors.red[600],
            icon: appTheme.colors.red[400],
            surface: appTheme.colors.red[200],
          },
          neutral: {
            border: appTheme.colors.gray[400],
            fill: appTheme.colors.gray[400],
            fillHover: appTheme.colors.gray[500],
            fillOnFill: appTheme.colors.common.white,
            fillPressed: appTheme.colors.gray[600],
            icon: appTheme.colors.gray[400],
            surface: appTheme.colors.gray[200],
          },
          notice: {
            border: appTheme.colors.yellow[400],
            fill: appTheme.colors.yellow[400],
            fillHover: appTheme.colors.yellow[500],
            fillOnFill: appTheme.colors.common.white,
            fillPressed: appTheme.colors.yellow[600],
            icon: appTheme.colors.yellow[400],
            surface: appTheme.colors.yellow[200],
          },
          positive: {
            border: appTheme.colors.green[400],
            fill: appTheme.colors.green[400],
            fillHover: appTheme.colors.green[500],
            fillOnFill: appTheme.colors.common.white,
            fillPressed: appTheme.colors.green[600],
            icon: appTheme.colors.green[400],
            surface: appTheme.colors.green[200],
          },
        },
        text: {
          action: {
            default: appTheme.colors.blue[400],
            hover: appTheme.colors.blue[500],
            pressed: appTheme.colors.blue[600],
          },
          base: {
            accent: appTheme.colors.blue[600],
            disabled: appTheme.colors.gray[300],
            onFill: appTheme.colors.common.white,
            onFillDisabled: appTheme.colors.gray[400],
            primary: appTheme.colors.common.black,
            secondary: appTheme.colors.gray[500],
          },
          beta: appTheme.colors.purple[600],
          info: appTheme.colors.blue[600],
          negative: appTheme.colors.red[600],
          neutral: appTheme.colors.gray[600],
          notice: appTheme.colors.yellow[600],
          positive: appTheme.colors.green[600],
        },
      },
      secondary: {
        "100": appTheme.colors.green[100],
        "200": appTheme.colors.green[200],
        "300": appTheme.colors.green[300],
        "400": appTheme.colors.green[400],
        "500": appTheme.colors.green[500],
        "600": appTheme.colors.green[600],
        contrastText: common.white,
        dark: appTheme.colors.green[600],
        light: appTheme.colors.green[200],
        main: appTheme.colors.green[400],
      },
      success: {
        "100": appTheme.colors.green[100],
        "200": appTheme.colors.green[200],
        "300": appTheme.colors.green[300],
        "400": appTheme.colors.green[400],
        "500": appTheme.colors.green[500],
        "600": appTheme.colors.green[600],
        contrastText: common.white,
        dark: appTheme.colors.green[600],
        light: appTheme.colors.green[200],
        main: appTheme.colors.green[400],
      },
      text: {
        disabled: appTheme.colors.gray[300],
        primary: common.black,
        secondary: appTheme.colors.gray[500],
      },
      warning: {
        "100": appTheme.colors.yellow[100],
        "200": appTheme.colors.yellow[200],
        "300": appTheme.colors.yellow[300],
        "400": appTheme.colors.yellow[400],
        "500": appTheme.colors.yellow[500],
        "600": appTheme.colors.yellow[600],
        contrastText: common.black,
        dark: appTheme.colors.yellow[600],
        light: appTheme.colors.yellow[200],
        main: appTheme.colors.yellow[400],
      },
    },
    shadows: [
      appTheme.shadows.none,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.s,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.m,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
      appTheme.shadows.l,
    ],
    shape: {
      borderRadius: appTheme.corners.m,
    },
    spacing: [
      appTheme.spacing.default,
      appTheme.spacing.xxxs,
      appTheme.spacing.xxs,
      appTheme.spacing.xs,
      appTheme.spacing.s,
      appTheme.spacing.m,
      appTheme.spacing.l,
      appTheme.spacing.xl,
      appTheme.spacing.xxl,
    ],
    transitions: {
      duration: {
        complex: 200,
        enteringScreen: 20,
        leavingScreen: 10,
        short: 150,
        shorter: 100,
        shortest: 50,
        standard: 200,
      },
      easing: {
        easeIn: "cubic-bezier(0, 0, 0.2, 1)",
        easeInOut: "cubic-bezier(0, 0, 0.2, 1)",
        easeOut: "cubic-bezier(0.0, 0, 0.2, 1)",
        sharp: "cubic-bezier(0, 0.2, 0.6, 1)",
      },
    },
    typography: {
      body1: appTheme.typography.styles.body.regular.xs,
      body2: appTheme.typography.styles.body.regular.xxs,
      button: appTheme.typography.styles.body.regular.button,
      caption: appTheme.typography.styles.body.regular.xxxs,
      fontFamily: `${appTheme.typography.fontFamily.body}, sans-serif`,
      h1: appTheme.typography.styles.header.semibold.xxl,
      h2: appTheme.typography.styles.header.semibold.xl,
      h3: appTheme.typography.styles.header.semibold.l,
      h4: appTheme.typography.styles.header.semibold.m,
      h5: appTheme.typography.styles.header.semibold.s,
      h6: appTheme.typography.styles.header.semibold.xs,
      overline: appTheme.typography.styles.caps.semibold.xxxs,
      subtitle1: appTheme.typography.styles.body.regular.xs,
      subtitle2: appTheme.typography.styles.header.semibold.xxs,
    },
  };
}
