import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8339-14285",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      useDivider: figma.boolean("showDivider?"),
      togglePosition: figma.enum("togglePosition", {
        left: "left",
        right: "right",
      }),
      // No matching props could be found for these Figma properties:
      // "showSubtitle": figma.boolean('showSubtitle?'),
      // "showDivider": figma.boolean('showDivider?'),
      // "slotContent": figma.instance('↪️ slotContent'),
      // "sdsStage": figma.enum('sdsStage', {
      //   "open": "open",
      //   "closed": "closed"
      // }),
      // "slotType": figma.enum('slotType', {
      //   "content": "content",
      //   "text": "text",
      //   "-": "-"
      // })
    },
    example: (props) => (
      <Index
        disabled={props.disabled}
        useDivider={props.useDivider}
        togglePosition={props.togglePosition}
      />
    ),
  }
);
