import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=12419%3A11055",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.instance("↪️ icon – large"),
      hover: figma.enum("state", {
        hover: true,
      }),
      sdsType: figma.enum("sdsType", {
        primary: "primary",
        secondary: "secondary",
      }),
      sdsStyle: figma.enum("sdsStyle", {
        square: "square",
        rounded: "rounded",
      }),
      // No matching props could be found for these Figma properties:
      // "iconLarge": figma.instance('↪️ icon – large'),
      // "iconSmall": figma.instance('↪️ icon – small'),
      // "showIcon": figma.boolean('showIcon?'),
      // "intent": figma.enum('intent', {
      //   "beta": "beta",
      //   "info": "info",
      //   "negative": "negative",
      //   "neutral": "neutral",
      //   "notice": "notice",
      //   "positive": "positive"
      // }),
      // "size": figma.enum('size', {
      //   "s": "s",
      //   "l": "l"
      // })
    },
    example: (props) => (
      <Index
        label="Tag label"
        icon={props.icon}
        hover={props.hover}
        sdsType={props.sdsType}
        sdsStyle={props.sdsStyle}
      />
    ),
  }
);
