import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8760%3A16015",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.instance("↪️ slotContent"),
      intent: figma.enum("intent", {
        info: "info",
        negative: "negative",
        notice: "notice",
        positive: "positive",
      }),
      sdsStage: figma.enum("sdsStage", {
        closed: "closed",
        open: "open",
      }),
      hideTitle: figma.boolean("showTitle?"),
      extraContent: figma.instance("↪️ slotContent"),
      sdsStyle: figma.enum("sdsStyle", {
        persistent: "persistent",
        expandable: "expandable",
        dismissible: "dismissible",
      }),
      // No matching props could be found for these Figma properties:
      // "showCalloutText": figma.boolean('showCalloutText?'),
      // "slotContent": figma.instance('↪️ slotContent'),
      // "showTitle": figma.boolean('showTitle?')
    },
    example: (props) => (
      <Index
        icon={props.icon}
        intent={props.intent}
        sdsStage={props.sdsStage}
        hideTitle={props.hideTitle}
        extraContent={props.extraContent}
        sdsStyle={props.sdsStyle}
      />
    ),
  }
);
