import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=9166%3A15154",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "showButtons": figma.boolean('showButtons?'),
      // "showArtworkSlot": figma.boolean('showArtworkSlot?'),
      // "dismissible": figma.boolean('dismissible?'),
      // "showOverlineText": figma.boolean('showOverlineText?'),
      // "showSubtitleText": figma.boolean('showSubtitleText?'),
      // "contentSlotContent": figma.instance('↪️ contentSlotContent'),
      // "artworkSlotContent": figma.instance('↪️ artworkSlotContent'),
      // "size": figma.enum('size', {
      //   "xs": "xs",
      //   "s": "s",
      //   "m": "m",
      //   "l": "l"
      // }),
      // "slotType": figma.enum('slotType', {
      //   "content": "content",
      //   "text": "text"
      // })
    },
    example: (_props) => <Index open={true} />,
  }
);
