import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8850%3A44694",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      intent: figma.enum("intent", {
        default: "default",
        negative: "negative",
        notice: "notice",
      }),
      state: figma.enum("state", {
        default: "default",
        open: "open",
      }),
      sdsStyle: figma.enum("sdsStyle", {
        minimal: "minimal",
        square: "square",
        rounded: "rounded",
      }),
      sdsType: figma.enum("sdsType", {
        label: "label",
        value: "value",
      }),
      // No matching props could be found for these Figma properties:
      // "showDetailsText": figma.boolean('showDetailsText?'),
      // "showIntentMessage": figma.boolean('showIntentMessage?'),
      // "selectionType": figma.enum('selectionType', {
      //   "counter": "counter",
      //   "value": "value",
      //   "-": "-"
      // })
    },
    example: (props) => (
      <Index
        disabled={props.disabled}
        intent={props.intent}
        label="Dropdown Label"
        onClick={() => {}}
        state={props.state}
        sdsStyle={props.sdsStyle}
        sdsType={props.sdsType}
      />
    ),
  }
);
