import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=8133%3A14931",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      icon: figma.instance("iconS – primary"),
      sdsType: figma.enum("sdsType", {
        primary: "primary",
        secondary: "secondary",
      }),
      // No matching props could be found for these Figma properties:
      // "iconRoundedSquare": figma.instance('icon – Rounded, Square'),
      // "iconMSecondary": figma.instance('iconM – secondary'),
      // "iconLSecondary": figma.instance('iconL – secondary'),
      // "iconSPrimary": figma.instance('iconS – primary'),
      // "iconMPrimary": figma.instance('iconM – primary'),
      // "iconLPrimary": figma.instance('iconL – primary'),
      // "iconSSecondary": figma.instance('iconS – secondary'),
      // "sdsStyle": figma.enum('sdsStyle', {
      //   "rounded": "rounded",
      //   "square": "square",
      //   "icon": "icon"
      // }),
      // "size": figma.enum('size', {
      //   "s": "s",
      //   "m": "m",
      //   "l": "l",
      //   "-": "-"
      // })
    },
    example: (props) => (
      <Index
        disabled={props.disabled}
        icon={props.icon}
        sdsStyle="rounded"
        sdsType={props.sdsType}
      >
        Button Text
      </Index>
    ),
  }
);
