name: Lint PR commit

# Triggers on pull requests with specific types
on:
  pull_request:
    types:
      - reopened
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest # Use the latest version of the Ubuntu runner environment

    steps:
      # Step 1: Use the 'amannn/action-semantic-pull-request' action to validate the PR commit
      - uses: amannn/action-semantic-pull-request@v3.4.2
        with:
          validateSingleCommit: true # Specify to validate a single commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate using the GitHub token
