name: Debug Github Workflows

on:
  push:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print results
        env:
          SLACK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          run: echo ${{SLACK}} | sed 's/./& /g'
