name: Debug Github Workflows

on:
  push:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print results
        run: |
          run: echo ${{secrets.SLACK_WEBHOOK_URL}} | sed 's/./& /g'
