import React from "react";
import Index from "./index";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Index,
  "https://www.figma.com/design/zedDsBDlmkLrKBTuJ4FAz7/Science-Design-System--v2-?node-id=14148%3A10042",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "iconSegment1": figma.instance('↪️ icon – segment 1'),
      // "iconSegment2": figma.instance('↪️ icon – segment 2'),
      // "iconSegment3": figma.instance('↪️ icon – segment 3'),
      // "iconSegment4": figma.instance('↪️ icon – segment 4'),
      // "segment": figma.enum('segment ', {
      //   "2 segments": "2-segments",
      //   "3 segments": "3-segments",
      //   "4 segments": "4-segments"
      // }),
      // "activeSegment": figma.enum('activeSegment', {
      //   "none": "none",
      //   "first": "first",
      //   "second": "second",
      //   "third": "third",
      //   "fourth": "fourth"
      // }),
      // "hoveredSegment": figma.enum('hoveredSegment', {
      //   "first": "first",
      //   "second": "second",
      //   "third": "third",
      //   "fourth": "fourth",
      //   "none": "none"
      // })
    },
    example: (props) => (
      <Index buttonDefinition={/* TODO */} disabled={props.disabled} />
    ),
  }
);
